// Code generated by "stringer -type=MessageRole,ContentType,StopReason,ThinkingLevel -output=llm_string.go llm.go"; DO NOT EDIT.

package llm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageRoleUser-0]
	_ = x[MessageRoleAssistant-1]
}

const _MessageRole_name = "MessageRoleUserMessageRoleAssistant"

var _MessageRole_index = [...]uint8{0, 15, 35}

func (i MessageRole) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageRole_index)-1 {
		return "MessageRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageRole_name[_MessageRole_index[idx]:_MessageRole_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentTypeText-2]
	_ = x[ContentTypeThinking-3]
	_ = x[ContentTypeRedactedThinking-4]
	_ = x[ContentTypeToolUse-5]
	_ = x[ContentTypeToolResult-6]
	_ = x[ContentTypeServerToolUse-7]
	_ = x[ContentTypeWebSearchToolResult-8]
	_ = x[ContentTypeWebSearchResult-9]
}

const _ContentType_name = "ContentTypeTextContentTypeThinkingContentTypeRedactedThinkingContentTypeToolUseContentTypeToolResultContentTypeServerToolUseContentTypeWebSearchToolResultContentTypeWebSearchResult"

var _ContentType_index = [...]uint8{0, 15, 34, 61, 79, 100, 124, 154, 180}

func (i ContentType) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_ContentType_index)-1 {
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentType_name[_ContentType_index[idx]:_ContentType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StopReasonStopSequence-24]
	_ = x[StopReasonMaxTokens-25]
	_ = x[StopReasonEndTurn-26]
	_ = x[StopReasonToolUse-27]
	_ = x[StopReasonRefusal-28]
	_ = x[StopReasonPause-29]
}

const _StopReason_name = "StopReasonStopSequenceStopReasonMaxTokensStopReasonEndTurnStopReasonToolUseStopReasonRefusalStopReasonPause"

var _StopReason_index = [...]uint8{0, 22, 41, 58, 75, 92, 107}

func (i StopReason) String() string {
	idx := int(i) - 24
	if i < 24 || idx >= len(_StopReason_index)-1 {
		return "StopReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StopReason_name[_StopReason_index[idx]:_StopReason_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThinkingLevelDefault-0]
	_ = x[ThinkingLevelOff-1]
	_ = x[ThinkingLevelMinimal-2]
	_ = x[ThinkingLevelLow-3]
	_ = x[ThinkingLevelMedium-4]
	_ = x[ThinkingLevelHigh-5]
	_ = x[ThinkingLevelXHigh-6]
}

const _ThinkingLevel_name = "ThinkingLevelDefaultThinkingLevelOffThinkingLevelMinimalThinkingLevelLowThinkingLevelMediumThinkingLevelHighThinkingLevelXHigh"

var _ThinkingLevel_index = [...]uint8{0, 20, 36, 56, 72, 91, 108, 126}

func (i ThinkingLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ThinkingLevel_index)-1 {
		return "ThinkingLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ThinkingLevel_name[_ThinkingLevel_index[idx]:_ThinkingLevel_index[idx+1]]
}
