import { build } from "esbuild";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { brotliCompressSync, constants } from "node:zlib";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "dist");
await mkdir(output, { recursive: true });
await Promise.all(
  ["app.js", "app.js.gz", "app.js.br", "app.js.br.b64", "app.css", "app.css.br", "app.css.br.b64"].map((name) =>
    rm(path.join(output, name), { force: true })
  )
);
await build({
  absWorkingDir: root,
  bundle: true,
  entryPoints: ["src/main.ts"],
  entryNames: "app",
  assetNames: "[name]",
  outdir: output,
  format: "iife",
  legalComments: "eof",
  minify: true,
  sourcemap: false,
  target: ["chrome120"]
});
const javascriptPath = path.join(output, "app.js");
const javascript = await readFile(javascriptPath);
await writeFile(
  path.join(output, "app.js.br.b64"),
  `${brotliCompressSync(javascript, {
    params: { [constants.BROTLI_PARAM_QUALITY]: 11 }
  }).toString("base64")}\n`
);
await rm(javascriptPath);
const stylesheetPath = path.join(output, "app.css");
const stylesheet = await readFile(stylesheetPath);
await writeFile(
  path.join(output, "app.css.br.b64"),
  `${brotliCompressSync(stylesheet, {
    params: { [constants.BROTLI_PARAM_QUALITY]: 11 }
  }).toString("base64")}\n`
);
await rm(stylesheetPath);
await writeFile(path.join(output, "GENERATED"), "Generated by pnpm build; do not edit files in this directory directly.\n");
