#!/bin/sh
set -eu

source_dir="${1:-/Users/ramon/src/shelley}"
manifest="${2:-docs/shelley-upstream-test-contracts.tsv}"

if ! git -C "$source_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	printf 'missing Shelley reference checkout: %s\n' "$source_dir" >&2
	exit 1
fi

is_test_artifact() {
	case "$1" in
		*_test.go | *.test.ts | *.test.tsx | *.test.runner.ts | *.spec.ts | \
		test/* | */testdata/* | ui/e2e/* | ui/lazycue/* | \
		AGENT_TESTING.md | test_ci.sh | test_manual.sh | \
		ui/scripts/global-setup.ts | ui/scripts/run-tests.mjs | ui/scripts/show-screenshots.sh)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

tmp_manifest="$(mktemp)"
trap 'rm -f "$tmp_manifest"' EXIT HUP INT TERM
revision="$(git -C "$source_dir" rev-parse HEAD)"
{
	printf '# Generated by scripts/generate-shelley-test-contracts.sh\n'
	printf '# Shelley revision: %s\n' "$revision"
	printf '# kind<TAB>path<TAB>contract\n'
} >"$tmp_manifest"

git -C "$source_dir" ls-files | LC_ALL=C sort | while IFS= read -r path; do
	if ! is_test_artifact "$path"; then
		continue
	fi
	printf 'artifact\t%s\t-\n' "$path"
	case "$path" in
		*_test.go)
			awk '
				/^func (Test|Benchmark|Fuzz)[A-Za-z0-9_]*\(/ {
					name = $2
					sub(/\(.*/, "", name)
					printf "go_case\t%s\t%s\n", path, name
				}
			' path="$path" "$source_dir/$path"
			;;
		*.ts | *.tsx | *.js | *.mjs)
			count="$(awk '
				{
					line = $0
					while (match(line, /(describe|it|test)(\.[A-Za-z]+)?[[:space:]]*\(/)) {
						count++
						line = substr(line, RSTART + RLENGTH)
					}
				}
				END { print count + 0 }
			' "$source_dir/$path")"
			printf 'js_case_count\t%s\t%s\n' "$path" "$count"
			;;
	esac
done >>"$tmp_manifest"

mv "$tmp_manifest" "$manifest"
trap - EXIT HUP INT TERM
