#!/bin/sh
set -eu

source_dir="${1:-/Users/ramon/src/shelley}"
destination_dir="${2:-examples/shelley}"
manifest="${3:-docs/shelley-upstream-tests.sha256}"

if ! git -C "$source_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	printf 'missing Shelley reference checkout: %s\n' "$source_dir" >&2
	exit 1
fi

tmp_manifest="$(mktemp)"
trap 'rm -f "$tmp_manifest"' EXIT HUP INT TERM

is_test_artifact() {
	case "$1" in
		*_test.go | *.test.ts | *.test.tsx | *.test.runner.ts | *.spec.ts | \
		test/* | */testdata/* | ui/e2e/* | ui/lazycue/* | \
		AGENT_TESTING.md | test_ci.sh | test_manual.sh | \
		ui/scripts/global-setup.ts | ui/scripts/run-tests.mjs | ui/scripts/show-screenshots.sh)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

revision="$(git -C "$source_dir" rev-parse HEAD)"
printf '# Generated by scripts/sync-shelley-upstream-tests.sh\n' >"$tmp_manifest"
printf '# Shelley revision: %s\n' "$revision" >>"$tmp_manifest"

git -C "$source_dir" ls-files | LC_ALL=C sort | while IFS= read -r path; do
	if ! is_test_artifact "$path"; then
		continue
	fi
	mkdir -p "$destination_dir/$(dirname "$path")"
	cp "$source_dir/$path" "$destination_dir/$path"
	hash="$(shasum -a 256 "$source_dir/$path" | awk '{print $1}')"
	printf '%s  %s\n' "$hash" "$path"
done >>"$tmp_manifest"

mv "$tmp_manifest" "$manifest"
trap - EXIT HUP INT TERM
